ALTER TABLE FIDE_ALMACENADO_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_CANTONES_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_CARGOS_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_CARRITO_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_CATEGORIA_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_CONTACTO_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_DETALLE_PEDIDO_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_DIRECCIONES_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_DISTRITOS_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_ESTADOS_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_FACTURACION_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_INVENTARIO_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_METODOS_PAGO_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_PAISES_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_PEDIDOS_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_PRESENTACIONES_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_PRODUCTOS_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_PROVINCIAS_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_TIPO_USUARIO_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));

ALTER TABLE FIDE_USUARIOS_TB 
  ADD (FECHA_CREACION TIMESTAMP,
       FECHA_MODIFICACION TIMESTAMP,
       CREADO_POR VARCHAR2(100),
       MODIFICADO_POR VARCHAR2(100),
       ACCION VARCHAR2(100));