RENAME VW_ALMACENAMIENTO_LISTAR TO FIDE_ALMACENAMIENTO_LISTAR_V;

RENAME VW_CARRITO_DETALLE TO FIDE_CARRITO_DETALLE_V;

RENAME VW_CATEGORIAS_LISTAR TO FIDE_CATEGORIAS_LISTAR_V;

RENAME VW_LISTAR_PRODUCTOS TO FIDE_LISTAR_PRODUCTOS_V;

RENAME VW_LISTAR_PRODUCTOS_ADMIN TO FIDE_LISTAR_PRODUCTOS_ADMIN_V;

RENAME VW_PEDIDOS_LISTAR TO FIDE_PEDIDOS_LISTAR_V;

RENAME VW_PRESENTACIONES_LISTAR TO FIDE_PRESENTACIONES_LISTAR_V;

RENAME VW_PRODUCTOS_SIN_INVENTARIO TO FIDE_PRODUCTOS_SIN_INVENTARIO_V;
