create or replace PACKAGE FIDE_PROYECTO_FINAL_PKG AS
FUNCTION fide_total_pedidos_usuario_fn(
    p_usuario_id IN NUMBER
) RETURN NUMBER;

FUNCTION fide_verificar_stock_producto_fn(
    p_producto_id IN NUMBER
) RETURN NUMBER;

FUNCTION fide_obtener_direccion_fn(
    p_usuario_id IN NUMBER
) RETURN VARCHAR2;

FUNCTION fide_productos_categoria_fn(
    p_categoria_id IN NUMBER
) RETURN NUMBER ;

FUNCTION fide_obtener_nombre_usuario_fn(
    p_usuario_id IN NUMBER
) RETURN VARCHAR2;

FUNCTION fide_calcular_valor_carrito_fn(
    p_usuario_id IN NUMBER
) RETURN NUMBER;

FUNCTION fide_obtener_descripcion_producto_fn(
    p_producto_id IN NUMBER
) RETURN VARCHAR2;

FUNCTION fide_calcular_total_pedido_fn(
    p_pedido_id IN NUMBER
) RETURN NUMBER;

-- FIDE_ESTADOS_TB
PROCEDURE FIDE_ESTADOS_INSERTAR_SP (
    P_ESTADOS_ID_ESTADO IN NUMBER,
    P_NOMBRE_ESTADO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_ESTADOS_MODIFICAR_SP (
    P_ESTADOS_ID_ESTADO IN NUMBER,
    P_NOMBRE_ESTADO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

-- FIDE_PAISES_TB
PROCEDURE FIDE_PAISES_INSERTAR_SP (
    P_PAISES_ID_PAIS_PK IN NUMBER,
    P_NOMBRE_PAIS IN VARCHAR2
);

PROCEDURE FIDE_PAISES_MODIFICAR_SP (
    P_PAISES_ID_PAIS_PK IN NUMBER,
    P_NOMBRE_PAIS IN VARCHAR2
);

-- FIDE_PROVINCIAS_TB
PROCEDURE FIDE_PROVINCIAS_INSERTAR_SP (
    P_PROVINCIAS_ID_PROVINCIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_PROVINCIA IN VARCHAR2
);

PROCEDURE FIDE_PROVINCIAS_MODIFICAR_SP (
    P_PROVINCIAS_ID_PROVINCIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_PROVINCIA IN VARCHAR2
);

PROCEDURE FIDE_PROVINCIAS_ELIMINAR_SP (
    P_PROVINCIAS_ID_PROVINCIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_CANTONES_TB
PROCEDURE FIDE_CANTONES_INSERTAR_SP (
    P_CANTONES_ID_CANTON_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CANTON IN VARCHAR2
);

PROCEDURE FIDE_CANTONES_MODIFICAR_SP (
    P_CANTONES_ID_CANTON_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CANTON IN VARCHAR2
);

PROCEDURE FIDE_CANTONES_ELIMINAR_SP (
    P_CANTONES_ID_CANTON_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_DISTRITOS_TB
PROCEDURE FIDE_DISTRITOS_INSERTAR_SP (
    P_DISTRITOS_ID_DISTRITO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_DISTRITO IN VARCHAR2
);

PROCEDURE FIDE_DISTRITOS_MODIFICAR_SP (
    P_DISTRITOS_ID_DISTRITO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_DISTRITO IN VARCHAR2
);

PROCEDURE FIDE_DISTRITOS_ELIMINAR_SP (
    P_DISTRITOS_ID_DISTRITO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_CARGOS_TB
PROCEDURE FIDE_CARGOS_INSERTAR_SP (
    P_CARGOS_ID_CARGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CARGO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_CARGOS_MODIFICAR_SP (
    P_CARGOS_ID_CARGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CARGO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_CARGOS_ELIMINAR_SP (
    P_CARGOS_ID_CARGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_TIPO_USUARIO_TB
PROCEDURE FIDE_TIPO_USUARIO_INSERTAR_SP (
    P_TIPO_USUARIO_ID_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_CARGOS_ID_CARGO_FK IN NUMBER,
    P_NOMBRE_TIPO_USUARIO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_TIPO_USUARIO_MODIFICAR_SP (
    P_TIPO_USUARIO_ID_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_CARGOS_ID_CARGO_FK IN NUMBER,
    P_NOMBRE_TIPO_USUARIO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_TIPO_USUARIO_ELIMINAR_SP (
    P_TIPO_USUARIO_ID_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_USUARIOS_TB
PROCEDURE FIDE_USUARIOS_INSERTAR_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_TIPO_USUARIO_ID_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_CONTRASENA IN VARCHAR2
);

PROCEDURE FIDE_USUARIOS_MODIFICAR_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_TIPO_USUARIO_ID_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_CONTRASENA IN VARCHAR2
);

PROCEDURE FIDE_USUARIOS_ACTUALIZAR_EMAIL_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_EMAIL IN VARCHAR2
);

PROCEDURE FIDE_USUARIOS_ACTUALIZAR_TELEFONO_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_TELEFONO IN VARCHAR2
);

PROCEDURE FIDE_USUARIOS_ACTUALIZAR_CONTRASENA_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_CONTRASENA IN VARCHAR2
);

PROCEDURE FIDE_USUARIOS_ELIMINAR_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_DIRECCIONES_TB
PROCEDURE FIDE_DIRECCIONES_INSERTAR_SP (
    P_DIRECCION_ID_DIRECCION_PK IN NUMBER,
    P_USUARIOS_ID_USUARIO_FK IN NUMBER,
    P_PAISES_ID_PAIS_FK IN NUMBER,
    P_PROVINCIAS_ID_PROVINCIA_FK IN NUMBER,
    P_CANTONES_ID_CANTON_FK IN NUMBER,
    P_DISTRITOS_ID_DISTRITO_FK IN NUMBER,
    P_OTRAS_SENAS IN VARCHAR2,
    P_ESTADOS_ID_ESTADO IN NUMBER
);

PROCEDURE FIDE_DIRECCIONES_MODIFICAR_SP (
    P_DIRECCION_ID_DIRECCION_PK IN NUMBER,
    P_PAISES_ID_PAIS_FK IN NUMBER,
    P_PROVINCIAS_ID_PROVINCIA_FK IN NUMBER,
    P_CANTONES_ID_CANTON_FK IN NUMBER,
    P_DISTRITOS_ID_DISTRITO_FK IN NUMBER,
    P_OTRAS_SENAS IN VARCHAR2,
    P_ESTADOS_ID_ESTADO IN NUMBER
);

PROCEDURE FIDE_DIRECCIONES_ELIMINAR_SP (
    P_DIRECCION_ID_DIRECCION_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO IN NUMBER
);

-- FIDE_CONTACTO_TB
PROCEDURE FIDE_CONTACTO_INSERTAR_SP (
    P_CONTACTO_ID_CONTACTO_PK IN NUMBER,
    P_USUARIOS_ID_USUARIO_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_ASUNTO IN VARCHAR2,
    P_MENSAJE IN VARCHAR2,
    P_FECHA_ENVIO IN DATE
);

PROCEDURE FIDE_CONTACTO_MODIFICAR_SP (
    P_CONTACTO_ID_CONTACTO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_ASUNTO IN VARCHAR2,
    P_MENSAJE IN VARCHAR2,
    P_FECHA_ENVIO IN DATE
);

PROCEDURE FIDE_CONTACTO_ELIMINAR_SP (
    P_CONTACTO_ID_CONTACTO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_PRODUCTOS_TB
PROCEDURE FIDE_PRODUCTOS_INSERTAR_SP (
    P_PRODUCTO_ID_PRODUCTO_PK IN NUMBER,
    P_CATEGORIA_ID_CATEGORIA_FK IN NUMBER,
    P_PRESENTACIONES_ID_PRESENTACION_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_PRECIO_UNITARIO IN NUMBER
);

PROCEDURE FIDE_PRODUCTOS_MODIFICAR_SP (
    P_PRODUCTO_ID_PRODUCTO_PK IN NUMBER,
    P_CATEGORIA_ID_CATEGORIA_FK IN NUMBER,
    P_PRESENTACIONES_ID_PRESENTACION_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2,
    P_PRECIO_UNITARIO IN NUMBER
);

PROCEDURE FIDE_PRODUCTOS_ELIMINAR_SP (
    P_PRODUCTO_ID_PRODUCTO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_CARRITO_TB
PROCEDURE FIDE_CARRITO_INSERTAR_SP (
    P_CARRITO_ID_CARRITO_PK IN NUMBER,
    P_USUARIOS_ID_USUARIO_FK IN NUMBER,
    P_PRODUCTOS_ID_PRODUCTO_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_CANTIDAD IN NUMBER,
    P_FECHA_AGREGADO IN DATE
);

PROCEDURE FIDE_CARRITO_MODIFICAR_SP (
    P_CARRITO_ID_CARRITO_PK IN NUMBER,
    P_CANTIDAD IN NUMBER
);

PROCEDURE FIDE_CARRITO_ELIMINAR_SP (
    P_CARRITO_ID_CARRITO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_PEDIDOS_TB
PROCEDURE FIDE_PEDIDOS_INSERTAR_SP (
    P_PEDIDOS_ID_PEDIDO_PK IN NUMBER,
    P_USUARIOS_ID_USUARIO_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_FECHA_PEDIDO IN DATE,
    P_TOTAL IN NUMBER
);

PROCEDURE FIDE_PEDIDOS_MODIFICAR_SP (
    P_PEDIDOS_ID_PEDIDO_PK IN NUMBER,
    P_TOTAL IN NUMBER
);

PROCEDURE FIDE_PEDIDOS_ELIMINAR_SP (
    P_PEDIDOS_ID_PEDIDO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_DETALLE_PEDIDO_TB
PROCEDURE FIDE_DETALLE_PEDIDO_INSERTAR_SP (
    P_DETALLE_PEDIDO_ID_DETALLE_PK IN NUMBER,
    P_PEDIDOS_ID_PEDIDO_FK IN NUMBER,
    P_PRODUCTOS_ID_PRODUCTO_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_CANTIDAD IN NUMBER,
    P_PRECIO_UNITARIO IN NUMBER
);

PROCEDURE FIDE_DETALLE_PEDIDO_MODIFICAR_SP (
    P_DETALLE_PEDIDO_ID_DETALLE_PK IN NUMBER,
    P_CANTIDAD IN NUMBER,
    P_PRECIO_UNITARIO IN NUMBER
);

PROCEDURE FIDE_DETALLE_PEDIDO_ELIMINAR_SP (
    P_DETALLE_PEDIDO_ID_DETALLE_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_FACTURACION_TB
PROCEDURE FIDE_FACTURACION_INSERTAR_SP (
    P_FACTURACION_ID_FACTURA_PK IN NUMBER,
    P_PEDIDOS_ID_PEDIDO_FK IN NUMBER,
    P_METODOS_PAGO_ID_PAGO_FK IN NUMBER,
    P_FECHA_EMISION IN DATE,
    P_DESCUENTOS IN NUMBER,
    P_SUBTOTAL IN NUMBER,
    P_IVA IN NUMBER,
    P_TOTAL_FACTURADO IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

PROCEDURE FIDE_FACTURACION_MODIFICAR_SP (
    P_FACTURACION_ID_FACTURA_PK IN NUMBER,
    P_DESCUENTOS IN NUMBER,
    P_SUBTOTAL IN NUMBER,
    P_IVA IN NUMBER,
    P_TOTAL_FACTURADO IN NUMBER
);

PROCEDURE FIDE_FACTURACION_ELIMINAR_SP (
    P_FACTURACION_ID_FACTURA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_INVENTARIO_TB
PROCEDURE FIDE_INVENTARIO_INSERTAR_SP (
    P_INVENTARIO_ID_MOVIMIENTO_PK IN NUMBER,
    P_PRODUCTOS_ID_PRODUCTO_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_ALMACENADO_ID_ALMACENADO_FK IN NUMBER,
    P_CANTIDAD_STOCK IN NUMBER,
    P_FECHA_INGRESO IN DATE,
    P_OBSERVACIONES IN VARCHAR2
);

PROCEDURE FIDE_INVENTARIO_MODIFICAR_SP (
    P_INVENTARIO_ID_MOVIMIENTO_PK IN NUMBER,
    P_CANTIDAD_STOCK IN NUMBER,
    P_OBSERVACIONES IN VARCHAR2
);

PROCEDURE FIDE_INVENTARIO_ELIMINAR_SP (
    P_INVENTARIO_ID_MOVIMIENTO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_ALMACENADO_TB
PROCEDURE FIDE_ALMACENADO_INSERTAR_SP (
    P_ALMACENADO_ID_ALMACENADO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_DESCRIPCION_ALMACENADO IN VARCHAR2
);

PROCEDURE FIDE_ALMACENADO_MODIFICAR_SP (
    P_ALMACENADO_ID_ALMACENADO_PK IN NUMBER,
    P_DESCRIPCION_ALMACENADO IN VARCHAR2
);

PROCEDURE FIDE_ALMACENADO_ELIMINAR_SP (
    P_ALMACENADO_ID_ALMACENADO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_PRESENTACIONES_TB
PROCEDURE FIDE_PRESENTACIONES_INSERTAR_SP (
    P_PRESENTACIONES_ID_PRESENTACION_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_TIPO_PRESENTACION IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_PRESENTACIONES_MODIFICAR_SP (
    P_PRESENTACIONES_ID_PRESENTACION_PK IN NUMBER,
    P_TIPO_PRESENTACION IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_PRESENTACIONES_ELIMINAR_SP (
    P_PRESENTACIONES_ID_PRESENTACION_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_CATEGORIA_TB
PROCEDURE FIDE_CATEGORIA_INSERTAR_SP (
    P_CATEGORIA_ID_CATEGORIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CATEGORIA IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_CATEGORIA_MODIFICAR_SP (
    P_CATEGORIA_ID_CATEGORIA_PK IN NUMBER,
    P_NOMBRE_CATEGORIA IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_CATEGORIA_ELIMINAR_SP (
    P_CATEGORIA_ID_CATEGORIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);

-- FIDE_METODOS_PAGO_TB
PROCEDURE FIDE_METODOS_PAGO_INSERTAR_SP (
    P_METODOS_PAGO_ID_PAGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_METODO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_METODOS_PAGO_MODIFICAR_SP (
    P_METODOS_PAGO_ID_PAGO_PK IN NUMBER,
    P_NOMBRE_METODO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
);

PROCEDURE FIDE_METODOS_PAGO_ELIMINAR_SP (
    P_METODOS_PAGO_ID_PAGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
);
END FIDE_PROYECTO_FINAL_PKG;