--Va en Package
FUNCTION FIDE_GENERAR_ID_FACTURA_FN RETURN NUMBER;

--Va en PackageBody

--CREANDO FUNCION PARA ASIGNAR ID A FACTURA
FUNCTION FIDE_GENERAR_ID_FACTURA_FN RETURN NUMBER IS
    V_FECHA VARCHAR2(6);
    V_VALOR NUMBER;
BEGIN
    V_FECHA := TO_CHAR(SYSDATE, 'YYYYMM');
    V_VALOR := TO_NUMBER(V_FECHA || LPAD(FACTURA_ID_SEQ.NEXTVAL, 5, '0'));
    
    RETURN V_VALOR;
END;
