---CREANDO TABLAS;
CREATE TABLE FIDE_ESTADOS_TB(
ID_ESTADO NUMBER CONSTRAINT ESTADOS_ID_ESTADO_PK PRIMARY KEY,
NOMBRE_ESTADO VARCHAR(100),
DESCRIPCION VARCHAR(200)
);
/
CREATE TABLE FIDE_PAISES_TB(
ID_PAIS NUMBER CONSTRAINT PAISES_ID_PAIS_PK PRIMARY KEY,
NOMBRE_PAIS VARCHAR(200)
)
/
CREATE TABLE FIDE_PROVINCIAS_TB(
ID_PROVINCIA NUMBER CONSTRAINT PROVINCIAS_ID_PROVINCIA_PK PRIMARY KEY,
NOMBRE_PROVINCIA VARCHAR(200)
)
/
CREATE TABLE FIDE_CANTONES_TB(
ID_CANTON NUMBER CONSTRAINT CANTONES_ID_CANTON_PK PRIMARY KEY,
NOMBRE_CANTON VARCHAR(200)
)
/

CREATE TABLE FIDE_DISTRITOS_TB(
ID_DISTRITO NUMBER CONSTRAINT DISTRITOS_ID_DISTRITOS_PK PRIMARY KEY,
NOMBRE_DISTRITO VARCHAR(200)
)
/
CREATE TABLE FIDE_DIRECCIONES_TB(
ID_DIRECCION NUMBER CONSTRAINT DIRECCIONES_ID_DIRECCION_PK PRIMARY KEY,
PAIS NUMBER,
PROVINCIA NUMBER,
CANTON NUMBER,
DISTRITO NUMBER,
ID_ESTADO NUMBER,
OTRAS_SENAS VARCHAR2(400),

CONSTRAINT DIRECCIONES_ID_PAIS_FK FOREIGN KEY (PAIS)REFERENCES FIDE_PAISES_TB(ID_PAIS),
CONSTRAINT DIRECCIONES_ID_PROVINCIA_FK FOREIGN KEY (PROVINCIA)REFERENCES FIDE_PROVINCIAS_TB(ID_PROVINCIA),
CONSTRAINT DIRECCIONES_ID_CANTON_FK FOREIGN KEY (CANTON)REFERENCES FIDE_CANTONES_TB(ID_CANTON),
CONSTRAINT DIRECCIONES_ID_DISTRITO_FK FOREIGN KEY (DISTRITO)REFERENCES FIDE_DISTRITOS_TB(ID_DISTRITO),
CONSTRAINT DIRECCIONES_ID_ESTADO_FK FOREIGN KEY (ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)

)
/
CREATE TABLE FIDE_CARGOS_TB(
ID_CARGO NUMBER CONSTRAINT CARGOS_CARGO_ID_PK PRIMARY KEY,
ID_ESTADO NUMBER,
NOMBRE_CARGO VARCHAR2(200),
DESCRIPCION VARCHAR2(400),

CONSTRAINT CARGOS_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_TIPO_USUARIOS_TB(
ID_TIPO_USUARIO NUMBER CONSTRAINT TIPO_USUARIO_ID_PK PRIMARY KEY,
ID_ESTADO NUMBER,
ID_CARGO NUMBER,
NOMBRE_TIPO_USUARIO VARCHAR2(200),
DESCRIPCION VARCHAR2(400),

CONSTRAINT TIPO_USUARIOS_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT TIPO_USUARIOS_ID_CARGO_FK FOREIGN KEY(ID_CARGO)REFERENCES FIDE_CARGOS_TB(ID_CARGO)
)
/
CREATE TABLE FIDE_USUARIOS_TB(
ID_USUARIO NUMBER CONSTRAINT USUARIOS_ID_USUARIO_PK PRIMARY KEY,
ID_TIPO_USUARIO NUMBER,
ID_ESTADO NUMBER,
NOMBRE VARCHAR2(200),
EMAIL VARCHAR2(200),
TELEFONO VARCHAR2(200),
CONTRASENA VARCHAR2(100),

CONSTRAINT USUARIOS_ID_TIPO_USUARIO_FK FOREIGN KEY(ID_TIPO_USUARIO)REFERENCES FIDE_TIPO_USUARIOS_TB(ID_TIPO_USUARIO),
CONSTRAINT USUARIOS_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_CONTACTOS_TB(
ID_CONTACTO NUMBER CONSTRAINT CONTACTOS_ID_CONTACTO_PK PRIMARY KEY,
ID_USUARIO NUMBER,
ID_ESTADO NUMBER,
ASUNTO VARCHAR2(200),
MENSAJE VARCHAR2(500),
FECHA_ENVIO DATE,

CONSTRAINT CONTACTOS_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT CONTACTOS_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)REFERENCES FIDE_USUARIOS_TB(ID_USUARIO)
)
/
CREATE TABLE FIDE_CATEGORIAS_TB(
ID_CATEGORIA NUMBER CONSTRAINT CATEGORIAS_ID_CATEGORIA_PK PRIMARY KEY,
ID_ESTADO NUMBER,
NOMBRE_CATEGORIA VARCHAR2(200),
DESCRIPCION VARCHAR2(400),

CONSTRAINT CATEGORIAS_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_PRESENTACIONES_TB(
ID_PRESENTACION NUMBER CONSTRAINT PRESENTACIONES_ID_PRESENTACION_PK PRIMARY KEY,
ID_ESTADO NUMBER,
TIPO_PRESENTACION VARCHAR2(200),
DESCRIPCION VARCHAR2(400),

CONSTRAINT PRESENTACIONES_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_PRODUCTOS_TB(
ID_PRODUCTO NUMBER CONSTRAINT PRODUCTOS_ID_PRODUCTO_PK PRIMARY KEY,
ID_CATEGORIA NUMBER,
ID_PRESENTACION NUMBER,
ID_ESTADO NUMBER,
NOMBRE_PRODUCTO VARCHAR2(200),
DESCRIPCION VARCHAR2(400),
PRECIO_UNITARIO NUMBER(8,2),

CONSTRAINT PRODUCTOS_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT PRODUCTOS_ID_CATEGORIA_FK FOREIGN KEY(ID_CATEGORIA)REFERENCES FIDE_CATEGORIAS_TB(ID_CATEGORIA),
CONSTRAINT PRODUCTOS_ID_PRESENTACION_FK FOREIGN KEY(ID_PRESENTACION)REFERENCES FIDE_PRESENTACIONES_TB(ID_PRESENTACION)

)
/
CREATE TABLE FIDE_ALMACENADO_TB(
ID_ALMACENADO NUMBER CONSTRAINT ALMACENADO_ID_ALMACENADO_PK PRIMARY KEY,
ID_ESTADO NUMBER,
DESCRIPCION_ALMACENADO VARCHAR2(400),

CONSTRAINT ALMACENADO_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_INVENTARIO_TB(
ID_INVENTARIO NUMBER CONSTRAINT INVENTARIO_ID_INVENTARIO_PK PRIMARY KEY,
ID_PRODUCTO NUMBER,
ID_ALMACENADO NUMBER,
ID_ESTADO NUMBER,
CANTIDAD_STOCK NUMBER,
FECHA_INGRESO DATE,
OBSERVACIONES VARCHAR2(400),

CONSTRAINT INVENTARIO_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO),
CONSTRAINT INVENTARIO_ID_PRODUCTO_FK FOREIGN KEY(ID_PRODUCTO)REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO),
CONSTRAINT INVENTARIO_ID_ALMACENADO_FK FOREIGN KEY(ID_ALMACENADO)REFERENCES FIDE_ALMACENADO_TB(ID_ALMACENADO)
)
/
CREATE TABLE FIDE_PEDIDOS_TB(
ID_PEDIDO NUMBER CONSTRAINT PEDIDOS_ID_PEDIDO_PK PRIMARY KEY,
ID_USUARIO NUMBER,
ID_ESTADO NUMBER,
FECHA_PEDIDO DATE,
TOTAL NUMBER(8,2),

CONSTRAINT PEDIDOS_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)REFERENCES FIDE_USUARIOS_TB(ID_USUARIO),
CONSTRAINT PEDIDOS_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_DETALLE_PEDIDO_TB(
ID_DETALLE NUMBER CONSTRAINT DETALLE_PEDIDO_ID_DETALLE_PK PRIMARY KEY,
ID_PEDIDO NUMBER,
ID_PRODUCTO NUMBER,
ID_ESTADO NUMBER,
CANTIDAD NUMBER,
PRECIO_UNITARIO NUMBER(8,2),

CONSTRAINT DETALLE_PEDIDO_ID_PEDIDO_FK FOREIGN KEY(ID_PEDIDO)REFERENCES FIDE_PEDIDOS_TB(ID_PEDIDO),
CONSTRAINT DETALLE_PEDIDO_ID_PRODUCTO_FK FOREIGN KEY(ID_PRODUCTO)REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO),
CONSTRAINT DETALLE_PEDIDO_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_METODOS_PAGO_TB(
ID_METODO NUMBER CONSTRAINT METODOS_PAGO_ID_METODO_PK PRIMARY KEY,
ID_ESTADO NUMBER,
NOMBRE_METODO VARCHAR2(200),
DESCRIPCION VARCHAR2(400),

CONSTRAINT METODOS_PAGO_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_FACTURACION_TB(
ID_FACTURA NUMBER CONSTRAINT FACTURACION_ID_FACTURA_PK PRIMARY KEY,
ID_PEDIDO NUMBER,
ID_METODO NUMBER,
ID_ESTADO NUMBER,
FECHA_EMISION DATE,
DESCUENTOS NUMBER(5,2),
SUBTOTAL NUMBER(8,2),
IVA NUMBER(5,2),
TOTAL_FACTURADO NUMBER(8,2),

CONSTRAINT FACTURACION_ID_PEDIDO_FK FOREIGN KEY(ID_PEDIDO)REFERENCES FIDE_PEDIDOS_TB(ID_PEDIDO),
CONSTRAINT FACTURACION_ID_METODO_FK FOREIGN KEY(ID_METODO)REFERENCES FIDE_METODOS_PAGO_TB(ID_METODO),
CONSTRAINT FACTURACION_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)
/
CREATE TABLE FIDE_CARRITO_TB(
ID_CARRITO NUMBER CONSTRAINT CARRITO_ID_CARRITO_PK PRIMARY KEY,
ID_USUARIO NUMBER,
ID_PRODUCTO NUMBER,
ID_ESTADO NUMBER,
CANTIDAD NUMBER,
FECHA_AGREGADO DATE,

CONSTRAINT CARRITO_ID_USUARIO_FK FOREIGN KEY(ID_USUARIO)REFERENCES FIDE_USUARIOS_TB(ID_USUARIO),
CONSTRAINT CARRITO_ID_PRODUCTO_FK FOREIGN KEY(ID_PRODUCTO)REFERENCES FIDE_PRODUCTOS_TB(ID_PRODUCTO),
CONSTRAINT CARRITO_ID_ESTADO_FK FOREIGN KEY(ID_ESTADO)REFERENCES FIDE_ESTADOS_TB(ID_ESTADO)
)

COMMIT;
