-- CREAR PACKAGE
CREATE OR REPLACE PACKAGE FIDE_PROYECTO_FINAL_PKG AS

END FIDE_PROYECTO_FINAL_PKG;
--  CREAR EL CUERPO
CREATE OR REPLACE PACKAGE BODY FIDE_PROYECTO_FINAL_PKG AS

END FIDE_PROYECTO_FINAL_PKG;
