-- FIDE_ESTADOS_TB
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_ESTADOS_INSERTAR_SP (
    P_ESTADOS_ID_ESTADO IN NUMBER,
    P_NOMBRE_ESTADO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
)IS
BEGIN
    INSERT INTO FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK,NOMBRE_ESTADO,DESCRIPCION)
    VALUES (P_ESTADOS_ID_ESTADO, P_NOMBRE_ESTADO,P_DESCRIPCION);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END FIDE_ESTADOS_INSERTAR_SP;    
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_ESTADOS_MODIFICAR_SP (
    P_ESTADOS_ID_ESTADO IN NUMBER,
    P_NOMBRE_ESTADO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
)IS
BEGIN
    UPDATE FIDE_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_ESTADO,
            DESCRIPCION = P_DESCRIPCION
    WHERE ESTADOS_ID_ESTADO_PK = P_ESTADOS_ID_ESTADO;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END FIDE_ESTADOS_MODIFICAR_SP;    
/
-- FIDE_PAISES_TB 
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_PAISES_INSERTAR_SP (
    P_PAISES_ID_PAIS_PK  IN NUMBER ,
    P_NOMBRE_PAIS IN VARCHAR2
)IS
BEGIN
    INSERT INTO FIDE_PAISES_TB (PAISES_ID_PAIS_PK, NOMBRE_PAIS)
    VALUES (P_PAISES_ID_PAIS_PK, P_NOMBRE_PAIS);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END FIDE_PAISES_INSERTAR_SP;
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_PAISES_MODIFICAR_SP (
    P_PAISES_ID_PAIS_PK  IN NUMBER ,
    P_NOMBRE_PAIS IN VARCHAR2
)IS
BEGIN
    UPDATE FIDE_PAISES_TB
    SET NOMBRE_PAIS = P_NOMBRE_PAIS
    WHERE PAISES_ID_PAIS_PK = P_PAISES_ID_PAIS_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END FIDE_PAISES_MODIFICAR_SP;
/
-- FIDE_PROVINCIAS_TB 
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_PROVINCIAS_INSERTAR_SP (
    P_PROVINCIAS_ID_PROVINCIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_PROVINCIA IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_PROVINCIAS_TB (PROVINCIAS_ID_PROVINCIA_PK, ESTADOS_ID_ESTADO_FK,NOMBRE_PROVINCIA) 
    VALUES (P_PROVINCIAS_ID_PROVINCIA_PK,P_ESTADOS_ID_ESTADO_FK,P_NOMBRE_PROVINCIA);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_PROVINCIAS_INSERTAR_SP;
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_PROVINCIAS_MODIFICAR_SP (
    P_PROVINCIAS_ID_PROVINCIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_PROVINCIA IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_PROVINCIAS_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK,
            NOMBRE_PROVINCIA = P_NOMBRE_PROVINCIA
    WHERE PROVINCIAS_ID_PROVINCIA_PK = P_PROVINCIAS_ID_PROVINCIA_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_PROVINCIAS_MODIFICAR_SP;

-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_PROVINCIAS_ELIMINAR_SP (
    P_PROVINCIAS_ID_PROVINCIA_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
) IS
BEGIN
    UPDATE FIDE_PROVINCIAS_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK
    WHERE PROVINCIAS_ID_PROVINCIA_PK = P_PROVINCIAS_ID_PROVINCIA_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_PROVINCIAS_ELIMINAR_SP;
/
-- FIDE_CANTONES_TB 
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_CANTONES_INSERTAR_SP (
    P_CANTONES_ID_CANTON_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CANTON IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_CANTONES_TB (CANTONES_ID_CANTON_PK, ESTADOS_ID_ESTADO_FK,NOMBRE_CANTON) 
    VALUES (P_CANTONES_ID_CANTON_PK,P_ESTADOS_ID_ESTADO_FK,P_NOMBRE_CANTON);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CANTONES_INSERTAR_SP;
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_CANTONES_MODIFICAR_SP (
    P_CANTONES_ID_CANTON_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CANTON IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_CANTONES_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK,
            NOMBRE_CANTON = P_NOMBRE_CANTON
    WHERE CANTONES_ID_CANTON_PK = P_CANTONES_ID_CANTON_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CANTONES_MODIFICAR_SP;

-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_CANTONES_ELIMINAR_SP (
     P_CANTONES_ID_CANTON_PK IN NUMBER,
     P_ESTADOS_ID_ESTADO_FK IN NUMBER
) IS
BEGIN
    UPDATE FIDE_CANTONES_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK
    WHERE CANTONES_ID_CANTON_PK = P_CANTONES_ID_CANTON_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CANTONES_ELIMINAR_SP;
-- FIDE_DISTRITOS_TB 
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_DISTRITOS_INSERTAR_SP (
    P_DISTRITOS_ID_DISTRITO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_DISTRITO IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_DISTRITOS_TB (DISTRITOS_ID_DISTRITO_PK,ESTADOS_ID_ESTADO_FK,NOMBRE_DISTRITO) 
    VALUES (P_DISTRITOS_ID_DISTRITO_PK,P_ESTADOS_ID_ESTADO_FK,P_NOMBRE_DISTRITO);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_DISTRITOS_INSERTAR_SP;
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_DISTRITOS_MODIFICAR_SP (
    P_DISTRITOS_ID_DISTRITO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_DISTRITO IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_DISTRITOS_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK,
            NOMBRE_DISTRITO = P_NOMBRE_DISTRITO
    WHERE DISTRITOS_ID_DISTRITO_PK = P_DISTRITOS_ID_DISTRITO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_DISTRITOS_MODIFICAR_SP;
/
-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_DISTRITOS_ELIMINAR_SP  (
    P_DISTRITOS_ID_DISTRITO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
) IS
BEGIN
    UPDATE FIDE_DISTRITOS_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK
    WHERE DISTRITOS_ID_DISTRITO_PK = P_DISTRITOS_ID_DISTRITO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_DISTRITOS_ELIMINAR_SP;
/
-- FIDE_CARGOS_TB
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_CARGOS_INSERTAR_SP (
    P_CARGOS_ID_CARGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CARGO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_CARGOS_TB (CARGOS_ID_CARGO_PK,ESTADOS_ID_ESTADO_FK,NOMBRE_CARGO,DESCRIPCION) 
        VALUES (P_CARGOS_ID_CARGO_PK,P_ESTADOS_ID_ESTADO_FK,P_NOMBRE_CARGO,P_DESCRIPCION);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CARGOS_INSERTAR_SP;
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_CARGOS_MODIFICAR_SP (
    P_CARGOS_ID_CARGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE_CARGO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_CARGOS_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK,
            NOMBRE_CARGO = P_NOMBRE_CARGO,
            DESCRIPCION = P_DESCRIPCION
    WHERE CARGOS_ID_CARGO_PK = P_CARGOS_ID_CARGO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CARGOS_MODIFICAR_SP;
/
-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_CARGOS_ELIMINAR_SP (
    P_CARGOS_ID_CARGO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
) IS
BEGIN
    UPDATE FIDE_CARGOS_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK
    WHERE CARGOS_ID_CARGO_PK = P_CARGOS_ID_CARGO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CARGOS_ELIMINAR_SP;
/
-- FIDE_TIPO_USUARIO_TB
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_TIPO_USUARIO_INSERTAR_SP (
    P_TIPO_USUARIO_ID_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_CARGOS_ID_CARGO_FK IN NUMBER,
    P_NOMBRE_TIPO_USUARIO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_TIPO_USUARIO_TB (TIPO_USUARIO_ID_PK,ESTADOS_ID_ESTADO_FK,CARGOS_ID_CARGO_FK,NOMBRE_TIPO_USUARIO,DESCRIPCION) 
    VALUES (P_TIPO_USUARIO_ID_PK,P_ESTADOS_ID_ESTADO_FK,P_CARGOS_ID_CARGO_FK,P_NOMBRE_TIPO_USUARIO,P_DESCRIPCION);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_TIPO_USUARIO_INSERTAR_SP;
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_TIPO_USUARIO_MODIFICAR_SP (
    P_TIPO_USUARIO_ID_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_CARGOS_ID_CARGO_FK IN NUMBER,
    P_NOMBRE_TIPO_USUARIO IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_TIPO_USUARIO_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK,
            CARGOS_ID_CARGO_FK = P_CARGOS_ID_CARGO_FK,
            NOMBRE_TIPO_USUARIO = P_NOMBRE_TIPO_USUARIO,
            DESCRIPCION = P_DESCRIPCION
    WHERE TIPO_USUARIO_ID_PK = P_TIPO_USUARIO_ID_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_TIPO_USUARIO_MODIFICAR_SP;
/
-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_TIPO_USUARIO_ELIMINAR_SP (
    P_TIPO_USUARIO_ID_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
) IS
BEGIN
    UPDATE FIDE_TIPO_USUARIO_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK
    WHERE TIPO_USUARIO_ID_PK = P_TIPO_USUARIO_ID_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_TIPO_USUARIO_ELIMINAR_SP;
/
-- FIDE_USUARIOS_TB
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_INSERTAR_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_TIPO_USUARIO_ID_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_CONTRASENA IN VARCHAR2
) IS
BEGIN
    INSERT INTO FIDE_USUARIOS_TB (USUARIO_ID_USUARIO_PK,TIPO_USUARIO_ID_FK,ESTADOS_ID_ESTADO_FK,NOMBRE,EMAIL,TELEFONO,CONTRASENA) 
    VALUES (P_USUARIO_ID_USUARIO_PK,P_TIPO_USUARIO_ID_FK,P_ESTADOS_ID_ESTADO_FK,P_NOMBRE,P_EMAIL,P_TELEFONO,P_CONTRASENA);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_USUARIOS_INSERTAR_SP;
/

-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_MODIFICAR_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_TIPO_USUARIO_ID_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_EMAIL IN VARCHAR2,
    P_TELEFONO IN VARCHAR2,
    P_CONTRASENA IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_USUARIOS_TB
    SET TIPO_USUARIO_ID_FK = P_TIPO_USUARIO_ID_FK,
            ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK,
            NOMBRE = P_NOMBRE,
            EMAIL = P_EMAIL,
            TELEFONO = P_TELEFONO,
            CONTRASENA = P_CONTRASENA
    WHERE USUARIO_ID_USUARIO_PK = P_USUARIO_ID_USUARIO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_USUARIOS_MODIFICAR_SP;
-- Modificar email
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_ACTUALIZAR_EMAIL_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_EMAIL IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_USUARIOS_TB
    SET EMAIL = P_EMAIL
    WHERE USUARIO_ID_USUARIO_PK = P_USUARIO_ID_USUARIO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR al actualizar email: ' || SQLERRM);
END FIDE_USUARIOS_ACTUALIZAR_EMAIL_SP;
/
-- Modificar telefono
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_ACTUALIZAR_TELEFONO_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_TELEFONO IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_USUARIOS_TB
    SET TELEFONO = P_TELEFONO
    WHERE USUARIO_ID_USUARIO_PK = P_USUARIO_ID_USUARIO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR al actualizar teléfono: ' || SQLERRM);
END FIDE_USUARIOS_ACTUALIZAR_TELEFONO_SP;
/
-- Modificar contraseña
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_ACTUALIZAR_CONTRASENA_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_CONTRASENA IN VARCHAR2
) IS
BEGIN
    UPDATE FIDE_USUARIOS_TB
    SET CONTRASENA = P_CONTRASENA
    WHERE USUARIO_ID_USUARIO_PK = P_USUARIO_ID_USUARIO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR al actualizar contraseña: ' || SQLERRM);
END FIDE_USUARIOS_ACTUALIZAR_CONTRASENA_SP;
/
-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_USUARIOS_ELIMINAR_SP (
    P_USUARIO_ID_USUARIO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
) IS
BEGIN
    UPDATE FIDE_USUARIOS_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK
    WHERE USUARIO_ID_USUARIO_PK = P_USUARIO_ID_USUARIO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_USUARIOS_ELIMINAR_SP;
/
-- FIDE_DIRECCIONES_TB
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_DIRECCIONES_INSERTAR_SP (
    P_DIRECCION_ID_DIRECCION_PK IN NUMBER,
    P_USUARIOS_ID_USUARIO_FK IN NUMBER,
    P_PAISES_ID_PAIS_FK IN NUMBER,
    P_PROVINCIAS_ID_PROVINCIA_FK IN NUMBER,
    P_CANTONES_ID_CANTON_FK IN NUMBER,
    P_DISTRITOS_ID_DISTRITO_FK IN NUMBER,
    P_OTRAS_SENAS IN VARCHAR2,
    P_ESTADOS_ID_ESTADO IN NUMBER
) IS
BEGIN
    INSERT INTO FIDE_DIRECCIONES_TB (DIRECCION_ID_DIRECCION_PK,USUARIOS_ID_USUARIO_FK,PAISES_ID_PAIS_FK,PROVINCIAS_ID_PROVINCIA_FK,CANTONES_ID_CANTON_FK,DISTRITOS_ID_DISTRITO_FK,OTRAS_SENAS,ESTADOS_ID_ESTADO_FK) 
    VALUES (P_DIRECCION_ID_DIRECCION_PK,P_USUARIOS_ID_USUARIO_FK,P_PAISES_ID_PAIS_FK,P_PROVINCIAS_ID_PROVINCIA_FK,P_CANTONES_ID_CANTON_FK,P_DISTRITOS_ID_DISTRITO_FK,P_OTRAS_SENAS,P_ESTADOS_ID_ESTADO);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_DIRECCIONES_INSERTAR_SP;
/

-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_DIRECCIONES_MODIFICAR_SP (
    P_DIRECCION_ID_DIRECCION_PK IN NUMBER,
    P_PAISES_ID_PAIS_FK IN NUMBER,
    P_PROVINCIAS_ID_PROVINCIA_FK IN NUMBER,
    P_CANTONES_ID_CANTON_FK IN NUMBER,
    P_DISTRITOS_ID_DISTRITO_FK IN NUMBER,
    P_OTRAS_SENAS IN VARCHAR2,
    P_ESTADOS_ID_ESTADO IN NUMBER
) IS
BEGIN
    UPDATE FIDE_DIRECCIONES_TB
    SET PAISES_ID_PAIS_FK = P_PAISES_ID_PAIS_FK,
            PROVINCIAS_ID_PROVINCIA_FK = P_PROVINCIAS_ID_PROVINCIA_FK,
            CANTONES_ID_CANTON_FK = P_CANTONES_ID_CANTON_FK,
            DISTRITOS_ID_DISTRITO_FK = P_DISTRITOS_ID_DISTRITO_FK,
            OTRAS_SENAS = P_OTRAS_SENAS,
            ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO
    WHERE DIRECCION_ID_DIRECCION_PK = P_DIRECCION_ID_DIRECCION_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_DIRECCIONES_MODIFICAR_SP;
/
-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_DIRECCIONES_ELIMINAR_SP (
    P_DIRECCION_ID_DIRECCION_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO IN NUMBER
) IS
BEGIN
    UPDATE FIDE_DIRECCIONES_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO
    WHERE DIRECCION_ID_DIRECCION_PK = P_DIRECCION_ID_DIRECCION_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_DIRECCIONES_ELIMINAR_SP;
/

-- FIDE_CONTACTO_TB
-- Inserción
CREATE OR REPLACE PROCEDURE FIDE_CONTACTO_INSERTAR_SP (
    P_CONTACTO_ID_CONTACTO_PK IN NUMBER,
    P_USUARIOS_ID_USUARIO_FK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_ASUNTO IN VARCHAR2,
    P_MENSAJE IN VARCHAR2,
    P_FECHA_ENVIO IN DATE
) IS
BEGIN
    INSERT INTO FIDE_CONTACTO_TB (CONTACTO_ID_CONTACTO_PK,USUARIOS_ID_USUARIO_FK,ESTADOS_ID_ESTADO_FK,ASUNTO,MENSAJE,FECHA_ENVIO) 
    VALUES (P_CONTACTO_ID_CONTACTO_PK,P_USUARIOS_ID_USUARIO_FK,P_ESTADOS_ID_ESTADO_FK,P_ASUNTO,P_MENSAJE,P_FECHA_ENVIO);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CONTACTO_INSERTAR_SP;
/
-- Modificación
CREATE OR REPLACE PROCEDURE FIDE_CONTACTO_MODIFICAR_SP (
    P_CONTACTO_ID_CONTACTO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER,
    P_ASUNTO IN VARCHAR2,
    P_MENSAJE IN VARCHAR2,
    P_FECHA_ENVIO IN DATE
) IS
BEGIN
    UPDATE FIDE_CONTACTO_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK,
            ASUNTO = P_ASUNTO,
            MENSAJE = P_MENSAJE,
            FECHA_ENVIO = P_FECHA_ENVIO
    WHERE CONTACTO_ID_CONTACTO_PK = P_CONTACTO_ID_CONTACTO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CONTACTO_MODIFICAR_SP;
/
-- Eliminación lógica
CREATE OR REPLACE PROCEDURE FIDE_CONTACTO_ELIMINAR_SP (
    P_CONTACTO_ID_CONTACTO_PK IN NUMBER,
    P_ESTADOS_ID_ESTADO_FK IN NUMBER
) IS
BEGIN
    UPDATE FIDE_CONTACTO_TB
    SET ESTADOS_ID_ESTADO_FK = P_ESTADOS_ID_ESTADO_FK
    WHERE CONTACTO_ID_CONTACTO_PK = P_CONTACTO_ID_CONTACTO_PK;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END FIDE_CONTACTO_ELIMINAR_SP;
/






