CREATE SEQUENCE ALMACENADO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CANTON_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CARGO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CARRITO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CATEGORIA_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE CONTACTO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE DETALLE_PEDIDO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE DIRECCION_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE DISTRITO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE ESTADO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE FACTURA_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE INVENTARIO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE METODO_PAGO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE PAIS_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE PEDIDO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE PRESENTACION_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE PRODUCTO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE PROVINCIA_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE TIPO_USUARIO_ID_SEQ
START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE USUARIO_ID_SEQ
START WITH 1 INCREMENT BY 1;