CREATE TABLE FIDE_ESTADOS_TB (
    ESTADOS_ID_ESTADO_PK NUMBER CONSTRAINT FIDE_ESTADOS_ID_ESTADO_PK PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(100) CONSTRAINT FIDE_ESTADOS_NOMBRE_NOT_NULL NOT NULL,
    DESCRIPCION VARCHAR2(255)
);

CREATE TABLE FIDE_PAISES_TB (
    PAISES_ID_PAIS_PK NUMBER CONSTRAINT FIDE_PAISES_ID_PAIS_PK PRIMARY KEY,
    NOMBRE_PAIS VARCHAR2(100) CONSTRAINT FIDE_PAISES_NOMBRE_NOT_NULL NOT NULL
);

CREATE TABLE FIDE_PROVINCIAS_TB (
    PROVINCIAS_ID_PROVINCIA_PK NUMBER CONSTRAINT FIDE_PROVINCIAS_ID_PROVINCIA_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_PROVINCIAS_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE_PROVINCIA VARCHAR2(100) CONSTRAINT FIDE_PROVINCIAS_NOMBRE_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_PROVINCIAS_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK)
    REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_CANTONES_TB (
    CANTONES_ID_CANTON_PK NUMBER CONSTRAINT FIDE_CANTONES_ID_CANTON_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_CANTONES_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE_CANTON VARCHAR2(100) CONSTRAINT FIDE_CANTONES_NOMBRE_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_CANTONES_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK)
    REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);


CREATE TABLE FIDE_DISTRITOS_TB (
    DISTRITOS_ID_DISTRITO_PK NUMBER CONSTRAINT FIDE_DISTRITOS_ID_DISTRITO_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_DISTRITOS_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE_DISTRITO VARCHAR2(100) CONSTRAINT FIDE_DISTRITOS_NOMBRE_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_DISTRITOS_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK)
    REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_CARGOS_TB (
    CARGOS_ID_CARGO_PK NUMBER CONSTRAINT FIDE_CARGOS_ID_CARGO_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_CARGOS_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE_CARGO VARCHAR2(100) CONSTRAINT FIDE_CARGOS_NOMBRE_NOT_NULL NOT NULL,
    DESCRIPCION VARCHAR2(255),
    CONSTRAINT FIDE_CARGOS_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK)
    REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_TIPO_USUARIO_TB (
    TIPO_USUARIO_ID_PK NUMBER CONSTRAINT FIDE_TIPO_USUARIO_ID_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_TIPO_USUARIO_ID_ESTADO_NOT_NULL NOT NULL,
    CARGOS_ID_CARGO_FK NUMBER CONSTRAINT FIDE_TIPO_USUARIO_ID_CARGO_NOT_NULL NOT NULL,
    NOMBRE_TIPO_USUARIO VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    CONSTRAINT FIDE_TIPO_USUARIO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_TIPO_USUARIO_ID_CARGO_FK FOREIGN KEY (CARGOS_ID_CARGO_FK) REFERENCES FIDE_CARGOS_TB (CARGOS_ID_CARGO_PK)
);

CREATE TABLE FIDE_USUARIOS_TB (
    USUARIO_ID_USUARIO_PK NUMBER CONSTRAINT FIDE_USUARIO_ID_USUARIO_PK PRIMARY KEY,
    TIPO_USUARIO_ID_FK NUMBER CONSTRAINT FIDE_USUARIO_ID_TIPO_NOT_NULL NOT NULL,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_USUARIO_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_USUARIOS_NOMBRE_NOT_NULL NOT NULL,
    EMAIL VARCHAR2(100) CONSTRAINT FIDE_USUARIOS_EMAIL_NOT_NULL NOT NULL,
    TELEFONO VARCHAR2(20),
    CONTRASENA VARCHAR2(100),
    CONSTRAINT FIDE_USUARIO_ID_TIPO_FK FOREIGN KEY (TIPO_USUARIO_ID_FK) REFERENCES FIDE_TIPO_USUARIO_TB (TIPO_USUARIO_ID_PK),
    CONSTRAINT FIDE_USUARIO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_DIRECCIONES_TB (
    DIRECCION_ID_DIRECCION_PK NUMBER CONSTRAINT FIDE_DIRECCIONES_ID_DIRECCION_PK PRIMARY KEY,
    USUARIOS_ID_USUARIO_FK NUMBER CONSTRAINT FIDE_DIRECCIONES_ID_USUARIO_NOT_NULL NOT NULL,
    PAISES_ID_PAIS_FK NUMBER CONSTRAINT FIDE_DIRECCIONES_ID_PAIS_NOT_NULL NOT NULL,
    PROVINCIAS_ID_PROVINCIA_FK NUMBER CONSTRAINT FIDE_DIRECCIONES_ID_PROVINCIA_NOT_NULL NOT NULL,
    CANTONES_ID_CANTON_FK NUMBER CONSTRAINT FIDE_DIRECCIONES_ID_CANTON_NOT_NULL NOT NULL,
    DISTRITOS_ID_DISTRITO_FK NUMBER CONSTRAINT FIDE_DIRECCIONES_ID_DISTRITO_NOT_NULL NOT NULL,
    OTRAS_SENAS VARCHAR2(255),
    CONSTRAINT FIDE_DIRECCIONES_ID_USUARIO_FK FOREIGN KEY (USUARIOS_ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB (USUARIO_ID_USUARIO_PK),
    CONSTRAINT FIDE_DIRECCIONES_ID_PAIS_FK FOREIGN KEY (PAISES_ID_PAIS_FK) REFERENCES FIDE_PAISES_TB (PAISES_ID_PAIS_PK),
    CONSTRAINT FIDE_DIRECCIONES_ID_PROVINCIA_FK FOREIGN KEY (PROVINCIAS_ID_PROVINCIA_FK) REFERENCES FIDE_PROVINCIAS_TB (PROVINCIAS_ID_PROVINCIA_PK),
    CONSTRAINT FIDE_DIRECCIONES_ID_CANTON_FK FOREIGN KEY (CANTONES_ID_CANTON_FK) REFERENCES FIDE_CANTONES_TB (CANTONES_ID_CANTON_PK),
    CONSTRAINT FIDE_DIRECCIONES_ID_DISTRITO_FK FOREIGN KEY (DISTRITOS_ID_DISTRITO_FK) REFERENCES FIDE_DISTRITOS_TB (DISTRITOS_ID_DISTRITO_PK)
);

CREATE TABLE FIDE_CONTACTO_TB (
    CONTACTO_ID_CONTACTO_PK NUMBER CONSTRAINT FIDE_CONTACTO_ID_CONTACTO_PK PRIMARY KEY,
    USUARIOS_ID_USUARIO_FK NUMBER CONSTRAINT FIDE_CONTACTO_ID_USUARIO_NOT_NULL NOT NULL,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_CONTACTO_ID_ESTADO_NOT_NULL NOT NULL,
    ASUNTO VARCHAR2(100),
    MENSAJE VARCHAR2(1000),
    FECHA_ENVIO DATE,
    CONSTRAINT FIDE_CONTACTO_ID_USUARIO_FK FOREIGN KEY (USUARIOS_ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB (USUARIO_ID_USUARIO_PK),
    CONSTRAINT FIDE_CONTACTO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_CATEGORIA_TB (
    CATEGORIA_ID_CATEGORIA_PK NUMBER CONSTRAINT FIDE_CATEGORIA_ID_CATEGORIA_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_CATEGORIA_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE_CATEGORIA VARCHAR2(100) CONSTRAINT FIDE_CATEGORIA_NOMBRE_NOT_NULL NOT NULL,
    DESCRIPCION VARCHAR2(255),
    CONSTRAINT FIDE_CATEGORIA_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_PRESENTACIONES_TB (
    PRESENTACIONES_ID_PRESENTACION_PK NUMBER CONSTRAINT FIDE_PRESENTACIONES_ID_PRESENTACION_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_PRESENTACIONES_ID_ESTADO_NOT_NULL NOT NULL,
    TIPO_PRESENTACION VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    CONSTRAINT FIDE_PRESENTACIONES_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_PRODUCTOS_TB (
    PRODUCTO_ID_PRODUCTO_PK NUMBER CONSTRAINT FIDE_PRODUCTOS_ID_PRODUCTO_PK PRIMARY KEY,
    CATEGORIA_ID_CATEGORIA_FK NUMBER CONSTRAINT FIDE_PRODUCTOS_ID_CATEGORIA_NOT_NULL NOT NULL,
    PRESENTACIONES_ID_PRESENTACION_FK NUMBER CONSTRAINT FIDE_PRODUCTOS_ID_PRESENTACION_NOT_NULL NOT NULL,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_PRODUCTOS_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE VARCHAR2(100) CONSTRAINT FIDE_PRODUCTOS_NOMBRE_NOT_NULL NOT NULL,
    DESCRIPCION VARCHAR2(255),
    PRECIO_UNITARIO NUMBER(10,2),
    CONSTRAINT FIDE_PRODUCTOS_ID_CATEGORIA_FK FOREIGN KEY (CATEGORIA_ID_CATEGORIA_FK) REFERENCES FIDE_CATEGORIA_TB (CATEGORIA_ID_CATEGORIA_PK),
    CONSTRAINT FIDE_PRODUCTOS_ID_PRESENTACION_FK FOREIGN KEY (PRESENTACIONES_ID_PRESENTACION_FK) REFERENCES FIDE_PRESENTACIONES_TB (PRESENTACIONES_ID_PRESENTACION_PK),
    CONSTRAINT FIDE_PRODUCTOS_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_ALMACENADO_TB (
    ALMACENADO_ID_ALMACENADO_PK NUMBER CONSTRAINT FIDE_ALMACENADO_ID_ALMACENADO_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_ALMACENADO_ID_ESTADO_NOT_NULL NOT NULL,
    DESCRIPCION_ALMACENADO VARCHAR2(255) CONSTRAINT FIDE_ALMACENADO_DESCRIPCION_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_ALMACENADO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_INVENTARIO_TB (
    INVENTARIO_ID_MOVIMIENTO_PK NUMBER CONSTRAINT FIDE_INVENTARIO_ID_MOVIMIENTO_PK PRIMARY KEY,
    PRODUCTOS_ID_PRODUCTO_FK NUMBER CONSTRAINT FIDE_INVENTARIO_ID_PRODUCTO_NOT_NULL NOT NULL,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_INVENTARIO_ID_ESTADO_NOT_NULL NOT NULL,
    ALMACENADO_ID_ALMACENADO_FK NUMBER CONSTRAINT FIDE_INVENTARIO_ID_ALMACENADO_NOT_NULL NOT NULL,
    CANTIDAD_STOCK NUMBER CONSTRAINT FIDE_INVENTARIO_CANTIDAD_NOT_NULL NOT NULL,
    FECHA_INGRESO DATE,
    OBSERVACIONES VARCHAR2(255),
    CONSTRAINT FIDE_INVENTARIO_ID_PRODUCTO_FK FOREIGN KEY (PRODUCTOS_ID_PRODUCTO_FK) REFERENCES FIDE_PRODUCTOS_TB (PRODUCTO_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_INVENTARIO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK),
    CONSTRAINT FIDE_INVENTARIO_ID_ALMACENADO_FK FOREIGN KEY (ALMACENADO_ID_ALMACENADO_FK) REFERENCES FIDE_ALMACENADO_TB (ALMACENADO_ID_ALMACENADO_PK)
);

CREATE TABLE FIDE_PEDIDOS_TB (
    PEDIDOS_ID_PEDIDO_PK NUMBER CONSTRAINT FIDE_PEDIDOS_ID_PEDIDO_PK PRIMARY KEY,
    USUARIOS_ID_USUARIO_FK NUMBER CONSTRAINT FIDE_PEDIDOS_ID_USUARIO_NOT_NULL NOT NULL,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_PEDIDOS_ID_ESTADO_NOT_NULL NOT NULL,
    FECHA_PEDIDO DATE,
    TOTAL NUMBER(10,2),
    CONSTRAINT FIDE_PEDIDOS_ID_USUARIO_FK FOREIGN KEY (USUARIOS_ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB (USUARIO_ID_USUARIO_PK),
    CONSTRAINT FIDE_PEDIDOS_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_DETALLE_PEDIDO_TB (
    DETALLE_PEDIDO_ID_DETALLE_PK NUMBER CONSTRAINT FIDE_DETALLE_PEDIDO_ID_DETALLE_PK PRIMARY KEY,
    PEDIDOS_ID_PEDIDO_FK NUMBER CONSTRAINT FIDE_DETALLE_PEDIDO_ID_PEDIDO_NOT_NULL NOT NULL,
    PRODUCTOS_ID_PRODUCTO_FK NUMBER CONSTRAINT FIDE_DETALLE_PEDIDO_ID_PRODUCTO_NOT_NULL NOT NULL,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_DETALLE_PEDIDO_ID_ESTADO_NOT_NULL NOT NULL,
    CANTIDAD NUMBER,
    PRECIO_UNITARIO NUMBER(10,2),
    CONSTRAINT FIDE_DETALLE_PEDIDO_ID_PEDIDO_FK FOREIGN KEY (PEDIDOS_ID_PEDIDO_FK) REFERENCES FIDE_PEDIDOS_TB (PEDIDOS_ID_PEDIDO_PK),
    CONSTRAINT FIDE_DETALLE_PEDIDO_ID_PRODUCTO_FK FOREIGN KEY (PRODUCTOS_ID_PRODUCTO_FK) REFERENCES FIDE_PRODUCTOS_TB (PRODUCTO_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_DETALLE_PEDIDO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_METODOS_PAGO_TB (
    METODOS_PAGO_ID_PAGO_PK NUMBER CONSTRAINT FIDE_METODOS_PAGO_ID_PAGO_PK PRIMARY KEY,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_METODOS_PAGO_ID_ESTADO_NOT_NULL NOT NULL,
    NOMBRE_METODO VARCHAR2(100) CONSTRAINT FIDE_METODOS_PAGO_NOMBRE_NOT_NULL NOT NULL,
    DESCRIPCION VARCHAR2(255),
    CONSTRAINT FIDE_METODOS_PAGO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_FACTURACION_TB (
    FACTURACION_ID_FACTURA_PK NUMBER CONSTRAINT FIDE_FACTURACION_ID_FACTURA_PK PRIMARY KEY,
    PEDIDOS_ID_PEDIDO_FK NUMBER CONSTRAINT FIDE_FACTURACION_ID_PEDIDO_NOT_NULL NOT NULL,
    METODOS_PAGO_ID_PAGO_FK NUMBER CONSTRAINT FIDE_FACTURACION_ID_PAGO_NOT_NULL NOT NULL,
    FECHA_EMISION DATE,
    DESCUENTOS NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    IVA NUMBER(10,2),
    TOTAL_FACTURADO NUMBER(10,2),
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_FACTURACION_ID_ESTADO_NOT_NULL NOT NULL,
    CONSTRAINT FIDE_FACTURACION_ID_PEDIDO_FK FOREIGN KEY (PEDIDOS_ID_PEDIDO_FK) REFERENCES FIDE_PEDIDOS_TB (PEDIDOS_ID_PEDIDO_PK),
    CONSTRAINT FIDE_FACTURACION_ID_PAGO_FK FOREIGN KEY (METODOS_PAGO_ID_PAGO_FK) REFERENCES FIDE_METODOS_PAGO_TB (METODOS_PAGO_ID_PAGO_PK),
    CONSTRAINT FIDE_FACTURACION_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);

CREATE TABLE FIDE_CARRITO_TB (
    CARRITO_ID_CARRITO_PK NUMBER CONSTRAINT FIDE_CARRITO_ID_CARRITO_PK PRIMARY KEY,
    USUARIOS_ID_USUARIO_FK NUMBER CONSTRAINT FIDE_CARRITO_ID_USUARIO_NOT_NULL NOT NULL,
    PRODUCTOS_ID_PRODUCTO_FK NUMBER CONSTRAINT FIDE_CARRITO_ID_PRODUCTO_NOT_NULL NOT NULL,
    ESTADOS_ID_ESTADO_FK NUMBER CONSTRAINT FIDE_CARRITO_ID_ESTADO_NOT_NULL NOT NULL,
    CANTIDAD NUMBER,
    FECHA_AGREGADO DATE,
    CONSTRAINT FIDE_CARRITO_ID_USUARIO_FK FOREIGN KEY (USUARIOS_ID_USUARIO_FK) REFERENCES FIDE_USUARIOS_TB (USUARIO_ID_USUARIO_PK),
    CONSTRAINT FIDE_CARRITO_ID_PRODUCTO_FK FOREIGN KEY (PRODUCTOS_ID_PRODUCTO_FK) REFERENCES FIDE_PRODUCTOS_TB (PRODUCTO_ID_PRODUCTO_PK),
    CONSTRAINT FIDE_CARRITO_ID_ESTADO_FK FOREIGN KEY (ESTADOS_ID_ESTADO_FK) REFERENCES FIDE_ESTADOS_TB (ESTADOS_ID_ESTADO_PK)
);



