CREATE OR REPLACE TRIGGER FIDE_ALMACENADO_INS_TRG
BEFORE INSERT ON FIDE_ALMACENADO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_ALMACENADO_UPD_TRG
BEFORE UPDATE ON FIDE_ALMACENADO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTONES_INS_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_CANTONES_UPD_TRG
BEFORE UPDATE ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CARGOS_INS_TRG
BEFORE INSERT ON FIDE_CARGOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_CARGOS_UPD_TRG
BEFORE UPDATE ON FIDE_CARGOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CARRITO_INS_TRG
BEFORE INSERT ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_CARRITO_UPD_TRG
BEFORE UPDATE ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INS_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_UPD_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_CONTACTO_INS_TRG
BEFORE INSERT ON FIDE_CONTACTO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_CONTACTO_UPD_TRG
BEFORE UPDATE ON FIDE_CONTACTO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_PEDIDO_INS_TRG
BEFORE INSERT ON FIDE_DETALLE_PEDIDO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_DETALLE_PEDIDO_UPD_TRG
BEFORE UPDATE ON FIDE_DETALLE_PEDIDO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_INS_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_DIRECCIONES_UPD_TRG
BEFORE UPDATE ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_INS_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_UPD_TRG
BEFORE UPDATE ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_INS_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_ESTADOS_UPD_TRG
BEFORE UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURACION_INS_TRG
BEFORE INSERT ON FIDE_FACTURACION_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_FACTURACION_UPD_TRG
BEFORE UPDATE ON FIDE_FACTURACION_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_INS_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_UPD_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_METODOS_PAGO_INS_TRG
BEFORE INSERT ON FIDE_METODOS_PAGO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_METODOS_PAGO_UPD_TRG
BEFORE UPDATE ON FIDE_METODOS_PAGO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAISES_INS_TRG
BEFORE INSERT ON FIDE_PAISES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_PAISES_UPD_TRG
BEFORE UPDATE ON FIDE_PAISES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PEDIDOS_INS_TRG
BEFORE INSERT ON FIDE_PEDIDOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_PEDIDOS_UPD_TRG
BEFORE UPDATE ON FIDE_PEDIDOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRESENTACIONES_INS_TRG
BEFORE INSERT ON FIDE_PRESENTACIONES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_PRESENTACIONES_UPD_TRG
BEFORE UPDATE ON FIDE_PRESENTACIONES_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_INS_TRG
BEFORE INSERT ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_UPD_TRG
BEFORE UPDATE ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_INS_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_UPD_TRG
BEFORE UPDATE ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_INS_TRG
BEFORE INSERT ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_UPD_TRG
BEFORE UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_INS_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_CREACION := SYSTIMESTAMP;
  :NEW.CREADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'INSERT';
END;
/
CREATE OR REPLACE TRIGGER FIDE_USUARIOS_UPD_TRG
BEFORE UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
  :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
  :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV','SESSION_USER');
  :NEW.ACCION := 'UPDATE';
END;
/