CREATE OR REPLACE TRIGGER FIDE_ESTADOS_ID_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADOS_ID_ESTADO_PK := ESTADO_ID_SEQ.NEXTVAL;
END;
/
CREATE OR REPLACE TRIGGER FIDE_ALMACENADO_ID_TRG
BEFORE INSERT ON FIDE_ALMACENADO_TB
FOR EACH ROW
BEGIN
    :NEW.ALMACENADO_ID_ALMACENADO_PK := ALMACENADO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CANTONES_ID_TRG
BEFORE INSERT ON FIDE_CANTONES_TB
FOR EACH ROW
BEGIN
    :NEW.CANTONES_ID_CANTON_PK := CANTON_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CARGOS_ID_TRG
BEFORE INSERT ON FIDE_CARGOS_TB
FOR EACH ROW
BEGIN
    :NEW.CARGOS_ID_CARGO_PK := CARGO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CARRITO_ID_TRG
BEFORE INSERT ON FIDE_CARRITO_TB
FOR EACH ROW
BEGIN
    :NEW.CARRITO_ID_CARRITO_PK := CARRITO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_ID_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.CATEGORIA_ID_CATEGORIA_PK := CATEGORIA_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_CONTACTO_ID_TRG
BEFORE INSERT ON FIDE_CONTACTO_TB
FOR EACH ROW
BEGIN
    :NEW.CONTACTO_ID_CONTACTO_PK := CONTACTO_ID_SEQ.NEXTVAL;
END;
/


CREATE OR REPLACE TRIGGER FIDE_DIRECCION_ID_TRG
BEFORE INSERT ON FIDE_DIRECCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.DIRECCION_ID_DIRECCION_PK := DIRECCION_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITOS_ID_TRG
BEFORE INSERT ON FIDE_DISTRITOS_TB
FOR EACH ROW
BEGIN
    :NEW.DISTRITOS_ID_DISTRITO_PK := DISTRITO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_ID_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.ESTADOS_ID_ESTADO_PK := ESTADO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_ID_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.INVENTARIO_ID_MOVIMIENTO_PK := INVENTARIO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_METODOS_PAGO_ID_TRG
BEFORE INSERT ON FIDE_METODOS_PAGO_TB
FOR EACH ROW
BEGIN
    :NEW.METODOS_PAGO_ID_PAGO_PK := METODO_PAGO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PAISES_ID_TRG
BEFORE INSERT ON FIDE_PAISES_TB
FOR EACH ROW
BEGIN
    :NEW.PAISES_ID_PAIS_PK := PAIS_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PEDIDOS_ID_TRG
BEFORE INSERT ON FIDE_PEDIDOS_TB
FOR EACH ROW
BEGIN
    :NEW.PEDIDOS_ID_PEDIDO_PK := PEDIDO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRESENTACIONES_ID_TRG
BEFORE INSERT ON FIDE_PRESENTACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.PRESENTACIONES_ID_PRESENTACION_PK := PRESENTACION_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTOS_ID_TRG
BEFORE INSERT ON FIDE_PRODUCTOS_TB
FOR EACH ROW
BEGIN
    :NEW.PRODUCTO_ID_PRODUCTO_PK := PRODUCTO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIAS_ID_TRG
BEFORE INSERT ON FIDE_PROVINCIAS_TB
FOR EACH ROW
BEGIN
    :NEW.PROVINCIAS_ID_PROVINCIA_PK := PROVINCIA_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_ID_TRG
BEFORE INSERT ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.TIPO_USUARIO_ID_PK := TIPO_USUARIO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_ID_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.USUARIO_ID_USUARIO_PK := USUARIO_ID_SEQ.NEXTVAL;
END;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURACION_ID_TRG
BEFORE INSERT ON FIDE_FACTURACION_TB
FOR EACH ROW
BEGIN
    :NEW.FACTURACION_ID_FACTURA_PK := FIDE_PROYECTO_FINAL_PKG.fide_generar_id_factura_fn;
END;
/
